#!/bin/bash
# =====================================================================
# make-macos-app.sh — build "Axona Portal.app" so the portal launches like
# an ordinary Mac application: one icon, no Terminal window.
#
#   bash scripts/make-macos-app.sh            # build beside the repo
#   bash scripts/make-macos-app.sh ~/Applications
#
# The bundle is a thin wrapper — it holds no copy of the code, it just runs
# scripts/launch.sh from THIS checkout. So `git pull` updates the app, and
# deleting the checkout correctly breaks it rather than leaving a stale copy
# running old code.
#
# Not code-signed. macOS will ask you to confirm the first launch
# (right-click -> Open, once). Signing it would need a paid Developer ID,
# which is not something a "clone the repo and run it" app should require.
# =====================================================================
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${1:-$REPO}"
APP="$DEST/Axona Portal.app"

[ -x "$REPO/scripts/launch.sh" ] || chmod +x "$REPO/scripts/launch.sh"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Axona Portal</string>
  <key>CFBundleDisplayName</key><string>Axona Portal</string>
  <key>CFBundleIdentifier</key><string>net.axona.portal</string>
  <key>CFBundleVersion</key><string>0.1.0</string>
  <key>CFBundleShortVersionString</key><string>0.1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>axona-portal</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST

cat > "$APP/Contents/MacOS/axona-portal" <<LAUNCHER
#!/bin/bash
# Generated by scripts/make-macos-app.sh — runs the launcher in the checkout
# this bundle was built from. AXONA_GUI=1 makes failures appear as a dialog:
# there is no Terminal here, so a message written to stderr would be lost and
# the app would look like it silently did nothing.
export AXONA_GUI=1
mkdir -p "\$HOME/.axona-portal"

# macOS TCC: an unsigned bundle launched by launchd has NO access to ~/Documents,
# ~/Desktop or ~/Downloads. If the checkout lives in one of those, the exec below
# fails with a bare "Operation not permitted" in a log nobody reads. Check first
# and say what to do. (Terminal already holds this permission, which is why the
# .command file works where this bundle does not.)
if [ ! -r "$REPO/scripts/launch.sh" ]; then
  osascript -e 'display dialog "macOS is blocking Axona Portal from reading its own files.

The checkout is in a protected folder (Documents, Desktop or Downloads), and an unsigned app cannot read those.

Two fixes, either works:
  • Use \"Axona Portal.command\" in the repo folder instead — it runs through Terminal, which already has permission.
  • Or move the checkout somewhere unprotected (e.g. ~/code/axona-portal) and rebuild this app.

You can also grant Full Disk Access to this app in System Settings > Privacy & Security." with title "Axona Portal" buttons {"OK"} default button 1 with icon caution' >/dev/null 2>&1
  exit 1
fi

exec "$REPO/scripts/launch.sh" >> "\$HOME/.axona-portal/launch.log" 2>&1
LAUNCHER
chmod +x "$APP/Contents/MacOS/axona-portal"

# A simple generated icon, so the Dock does not show a blank page. Drawn with
# the tools every Mac already has (no design assets to keep in the repo).
# One scratch DIRECTORY for both. (`mktemp` without -d makes a FILE; running
# mkdir on its path fails, and under `set -e` that aborted the whole script
# after the bundle was already written — it "worked" but silently skipped the
# icon and the success message.)
WORK="$(mktemp -d)"
ICONSET="$WORK/AppIcon.iconset"
SVG="$WORK/icon.svg"
mkdir -p "$ICONSET"
cat > "$SVG" <<'SVGEOF'
<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024">
  <rect width="1024" height="1024" rx="230" fill="#2f6f4f"/>
  <circle cx="512" cy="512" r="70" fill="#fbfbfa"/>
  <g stroke="#fbfbfa" stroke-width="26" fill="none" opacity="0.92">
    <circle cx="512" cy="512" r="200"/>
    <circle cx="512" cy="512" r="330"/>
  </g>
  <g fill="#fbfbfa">
    <circle cx="512" cy="312" r="42"/><circle cx="685" cy="612" r="42"/>
    <circle cx="339" cy="612" r="42"/><circle cx="512" cy="842" r="34"/>
    <circle cx="182" cy="512" r="34"/><circle cx="842" cy="512" r="34"/>
  </g>
</svg>
SVGEOF

if command -v qlmanage >/dev/null 2>&1 && command -v sips >/dev/null 2>&1; then
  PNG="$WORK/icon.png"
  qlmanage -t -s 1024 -o "$WORK" "$SVG" >/dev/null 2>&1 || true
  [ -f "$SVG.png" ] && mv "$SVG.png" "$PNG"
  if [ -f "$PNG" ]; then
    for s in 16 32 64 128 256 512; do
      sips -z $s $s "$PNG" --out "$ICONSET/icon_${s}x${s}.png" >/dev/null 2>&1
      sips -z $((s*2)) $((s*2)) "$PNG" --out "$ICONSET/icon_${s}x${s}@2x.png" >/dev/null 2>&1
    done
    iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/AppIcon.icns" 2>/dev/null || true
  fi
fi

# Nudge Finder to notice the new bundle (it caches icons aggressively).
touch "$APP"

echo "✓ built $APP"
echo
echo "  Double-click it to start the portal."
if [ -f "$APP/Contents/Resources/AppIcon.icns" ]; then
  echo "  Icon: generated."
else
  echo "  Icon: skipped (qlmanage/sips unavailable) — the app still works."
fi
echo "  First launch: macOS may warn it is from an unidentified developer —"
echo "  right-click the app once and choose Open, then it opens normally."
echo "  Logs: ~/.axona-portal/launch.log"
